Feature repository cell
devpass-tech/challenge-github-app pull request #193
Opened 2023-04-04 19:52 UTC by giseletoledo

- [x]  Implementar classe RepositoryCellView
- [x]  A classe deve ter 2 UILabels como subviews (nome do repositório, nome de usuário do dono do repositório)
- [x]  Deve ser possível configurar o texto a partir de um método `updateView(with configuration: RepositoryCellViewConfiguration)` da classe RepositoryCellView

2023-04-04 21:15 UTC, reisdev requested changes

2023-04-04 21:15 UTC, reisdev commented on solutions/devsprint-matheus-reis-8/GitHubApp/Screens/Components/RepositoryCellView.swift
> +    }
Separar esse método em `setupSubviews` e `setupConstraints` para melhor organização do código

2023-04-04 21:15 UTC, reisdev commented on solutions/devsprint-matheus-reis-8/GitHubApp/Screens/Components/RepositoryCellView.swift
> +    private let repositoryNameLabel: UILabel = {
Usar `lazy var` ao invés de `let` para declaração das subviews.

2023-04-04 21:15 UTC, reisdev commented on solutions/devsprint-matheus-reis-8/GitHubApp/Screens/Components/RepositoryCellView.swift
> +    private let userNameLabel: UILabel = {
Usar `lazy var` ao invés de `let` para declaração das subviews

2023-04-05 15:09 UTC, giseletoledo commented
Modifiquei conforme os comentários

2023-04-05 15:11 UTC, giseletoledo commented on solutions/devsprint-matheus-reis-8/GitHubApp/Screens/Components/RepositoryCellView.swift
> +    private let userNameLabel: UILabel = {
Modificado

2023-04-05 15:13 UTC, giseletoledo commented
Eu olhei os conflitos, mas não sei se a configuração ficou correta

2023-04-05 21:46 UTC, reisdev requested changes
- Remover arquivo vazio da pasta solutions
- Mover RepositoryCellView para a pasta Screens/Components

2023-04-05 22:30 UTC, merged