ImplementaçãoLoadingView
devpass-tech/challenge-github-app pull request #70
Opened 2022-01-19 17:22 UTC by feeforcinetti

* Implementação da Feature LoadingView
 
### Descrição simples da nova feature
 - Essa feature implementa um componente de interface constituído por uma UILabel e por um UIActivityIndicator.
 - Implementado uma estrutura para configurar o texto referente ao UILabel da feature
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
| iPhone 13 |
| ------ | ----
![Simulator Screen Shot - iPhone 13 - 2022-01-19 at 14 19 49](https://user-images.githubusercontent.com/67073291/150181692-85310bd6-377a-453b-9dcf-d337795ab86a.png)
-- |

2022-01-19 21:46 UTC, rdgborges requested changes
Boa @feeforcinetti! Deixei alguns comentários para melhorar o código e os padrões que seguimos. Dá uma olhada. ;)

2022-01-19 21:46 UTC, rdgborges commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Components/LoadingView/LoadingView.swift
> +        label.text = "Searching repositories..."
Remover essa linha por que a textLabel será configurada a partir do método `updateView(with configuration: LoadingViewConfiguration)`.

2022-01-19 21:46 UTC, rdgborges commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Components/LoadingView/LoadingView.swift
> +    lazy var indicatorView: UIActivityIndicatorView = {
Pode setar indicatorView como `private` pois não faz sentido ela estar exposta para fora da classe `LoadingView`.

2022-01-19 21:46 UTC, rdgborges commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Components/LoadingView/LoadingView.swift
> +    func configure(with viewModel: LoadingViewModel) {
Alterar nome do método para `updateView(with configuration: LoadingViewConfiguration)` (conforme os critérios de aceite).

2022-01-19 21:46 UTC, rdgborges commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Components/LoadingView/LoadingViewModel.swift
> +    let textLabel: String?
Nesse caso, não há necessidade de textLabel ser opcional, pois é esperado que ela sempre tenha um valor para usarmos na configuração da LoadingView.

2022-01-19 23:23 UTC, feeforcinetti commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Components/LoadingView/LoadingView.swift
> +    lazy var indicatorView: UIActivityIndicatorView = {
Boa Rodrigão, deixei passar esse private

2022-01-20 17:16 UTC, rdgborges approved these changes
Mandou bem @feeforcinetti! 🚀🚀🚀

2022-01-20 17:16 UTC, merged