Feature/Navigation and Configuration of Settings Screen
devpass-tech/challenge-github-app pull request #89
Opened 2022-01-21 22:36 UTC by enrickdaltro

### Descrição simples da nova feature
 
 - Add navigation to settings screen on ListView navigation bar as a NavigationRightIcon
 - Configure UITableView on Settings Screen
 - Show app version on UITableViewCell
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:
| iPhone 12|
| ----- |
|<img src="https://user-images.githubusercontent.com/49761746/150609080-1decb60b-c697-4ffa-82f0-4b1ac635d2dd.gif" width="250"  />|

2022-01-24 19:29 UTC, rdgborges requested changes
Sugestão: Uma pequena modificação para a configuração global da NavigationBar.

2022-01-24 19:29 UTC, rdgborges commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Settings/SettingsViewController.swift
> +        let appearance = UINavigationBarAppearance()
Configurações globais como essas podem estar no AppDelegate (Ex: método didFinishLaunchingWithOptions) para termos certeza que ela será aplicada à toda interface do app e não somente quando iniciarmos a `SettingsViewController`, como neste caso.

2022-01-25 11:53 UTC, enrickdaltro commented on solutions/devsprint-rodrigo-borges-1/GitHubApp/Screens/Settings/SettingsViewController.swift
> +        let appearance = UINavigationBarAppearance()
@rdgborges Ajustado 👍

2022-01-25 13:10 UTC, rdgborges approved these changes

2022-01-25 13:10 UTC, merged